version: '3'
services:
  note:
    # image: node:alpine
    build: ./note
    image: ${IMAGE_REPOSITORY}/note:${NOTE_VERSION}
    # command: node --inspect-brk=0.0.0.0:9229 concert_entrance_server.js
    ports:
      - "80:3001"
      # - "9229:9229"
    # volumes:
    #   - ./note:/home/node/note
    working_dir: '/home/node/note'

  scraping:
    build: ./scraping
    image: ${IMAGE_REPOSITORY}/scraping:${SCRAPING_VERSION}
    container_name: scraping
    # command: python concert_scraping.py --debug
    # ports:
    #   - "3000:3000"
    depends_on:
      - note
      - selenium-hub
    # volumes:
    #   - ./scraping:/root/scraping
    working_dir: '/root/scraping'

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
