version: '3'
services:
  note:
    # image: node:alpine
    build: ./web
    image: concert-entrance/note:v1.0
    # command: node --inspect-brk=0.0.0.0:9229 concert_entrance_server.js
    ports:
      - "3001:3001"
      # - "9229:9229"
    # volumes:
    #   - ./web:/home/node/web
    working_dir: '/home/node/web'

  scraping:
    build: ./scraping
    image: concert-entrance/scraping:v1.0
    container_name: scraping
    # command: python concert_scraping.py
    depends_on:
      - note
      - selenium-hub
    # volumes:
    #   - ./scraping:/root/scraping
    working_dir: '/root/scraping'

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
