version: '3'
services:
  node:
    # image: node:alpine
    build: ./web
    # command: node concert_entrance_server.js
    ports:
      - "3001:3001"
      - "9229:9229"
    # volumes:
    #   - ./web:/home/node/web
    # working_dir: '/home/node/web'

  scraping:
    build: ./scraping
    tty: true
    container_name: scraping
    # command: python concert_scraping.py
    depends_on:
      - node
      - chrome
    # volumes:
    #   - ./scraping:/root/scraping
    # working_dir: '/root/scraping'

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
