version: '3'
services:
  note:
    # image: node:alpine
    build: ./note
    image: ${IMAGE_REPOSITORY}/note:${NOTE_VERSION}
    # command: node --inspect-brk=0.0.0.0:9000 server.js
    ports:
      - "80:3000"
      # - "9000:9000"
    # volumes:
    #   - ./note:/home/node/note
    working_dir: '/home/node/note'

  scraping:
    build: ./scraping
    image: ${IMAGE_REPOSITORY}/scraping:${SCRAPING_VERSION}
    container_name: scraping
    # command: python concert_scraping.py --debug --local
    # ports:
    #   - "9500:9500"
    depends_on:
      - mysql
      - selenium-hub
    # volumes:
    #   - ./scraping:/root/scraping
    working_dir: '/root/scraping'

  mysql:
    build: ./mysql
    image: ${IMAGE_REPOSITORY}/mysql:${MYSQL_VERSION}
    env_file: ./mysql.env
    volumes:
      - ./volumes/mysql:/var/lib/mysql

  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
