apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: selenium-hub
        tier: backend
    spec:
      containers:
      - name: master
        image: selenium/hub
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 4444
