apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  labels:
    app: selenium-hub
    tier: backend
spec:
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: selenium-hub
    tier: backend
