apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: gcr.io/endless-upgrade-214504/mysql:v1.0
        imagePullPolicy: Always
