apiVersion: v1
kind: Service
metadata:
  name: note-debug
  labels:
    app: note-debug
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 9229
    targetPort: 9229
  selector:
    app: note
    tier: frontend
