apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chrome
        tier: backend
    spec:
      containers:
      - name: master
        image: selenium/node-chrome-debug
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: HUB_HOST
          value: selenium-hub
        - name: HUB_PORT
          value: '4444'
        ports:
        - containerPort: 4444
