apiVersion: v1
kind: Service
metadata:
  name: chrome
  labels:
    app: chrome
    tier: backend
spec:
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: chrome
    tier: backend
