apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: entrance
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: entrance
    tier: frontend
