apiVersion: v1
kind: Service
metadata:
  name: note-front
  labels:
    app: note-front
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
  selector:
    app: note
    tier: frontend
