apiVersion: v1
kind: Service
metadata:
  name: note
  labels:
    app: note
    tier: frontend
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: note
    tier: frontend
