apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: note
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: note
        tier: frontend
    spec:
      containers:
      - name: master
        image: concert-entrance/note:v1.0
        # volumeMounts:
        # - mountPath: /home/node/note
        #   name: note-debug-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3001
      # volumes:
      # - name: note-debug-volume
      #   hostPath:
      #     path: ${PROJECT_DIR}/note
      #     type: Directory
