apiVersion: v1
kind: Service
metadata:
  name: scraping-debug
  labels:
    app: scraping-debug
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: scraping
