apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-debug
  labels:
    app: selenium-hub-debug
spec:
  type: LoadBalancer
  ports:
  - port: 4444
    targetPort: 4444
  selector:
    app: selenium-hub
    tier: backend
