apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scraping
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: master
            image: concert-entrance/scraping:v1.0
            imagePullPolicy: Always
            env:
            - name: GET_HOSTS_FROM
              value: dns
          restartPolicy: OnFailure
