apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: note
spec:
  template:
    metadata:
      labels:
        app: note
        tier: frontend
    spec:
      containers:
      - name: master
        imagePullPolicy: IfNotPresent
        # command: [ "node", "--inspect-brk=0.0.0.0:9229", "concert_entrance_server.js" ]
        volumeMounts:
        - mountPath: /home/node/note
          name: note-debug-volume
        ports:
        - containerPort: 9229
      volumes:
      - name: note-debug-volume
        hostPath:
          path: //c/Users/ide/works/concert_entrance/note
          type: Directory
