apiVersion: v1
kind: Service
metadata:
  name: scraping-debug
  labels:
    app: scraping-debug
spec:
  type: LoadBalancer
  ports:
  - port: 9500
    targetPort: 9500
  selector:
    app: scraping
